### ISSUE TITLE
Ignore extra fields in responses

### ISSUE THREAD

**Issue by ul** [gluon-lang/lsp-types#101]
I wonder if it's possible to relax response type definitions to allow extra fields in it. See https://github.com/ul/kak-lsp/issues/173 for context.

**Comment by Marwes** [comment]
Plain structs already allow for extra fields when deserializing so this is only an issue for enums that use `untagged`. I suspect it isn't possible to make `untagged` work with extra fields but you could try asking over in https://github.com/serde-rs/serde/issues.

An alternative solution would be to implement a custom deserializer instead of relying on `untagged`, depending on how many `enum`s you need converted and how they look like this could be easy or hard however https://serde.rs/impl-deserialize.html

**Comment by vnagarnaik** [comment]
This is response from our resident LSP expert about ignoring extra fields:
> LSP Does not say that there should be no additional fields (at least when I last looked at the document). For example, there might be a more up-to-date version of the protocol which adds a new fields - your old lsp client will not know about this field. So it makes sense to assume that LSP clients should just ignore fields they do not understand (what VSCode, the canonical lsp client, does).

So if Rust/serde's untagged enum can't ignore unknown fields when deserializing, it would need to be changed. I assume other protocol implementations would also have similar needs.

**Comment by dtolnay** [comment]
Could someone put together a minimal repro in the playground involving an untagged enum and an extra field? As far as I know, untagged enums ignore extra fields just as much as structs do.

**Comment by ul** [comment]
I tried to reproduce it with the following code but was unable to do so.
```
use lsp_types::CompletionResponse;
use serde_json::Result;

fn main() {
    let no_extra = r#"
        {
          "isIncomplete": false,
          "items": [{"label": "A"}]
        }
    "#;
    let fine: Result<CompletionResponse> = serde_json::from_str(no_extra);
    println!("Fine: {:?}", fine);
    let with_extra = r#"
        {
          "isIncomplete": false,
          "items": [{"label": "A", "anotherCustomField": "Hello"}],
          "customField": "World"
        }
    "#;
    let fails: Result<CompletionResponse> = serde_json::from_str(with_extra);
    // actually doesn't fail
    println!("Fails: {:?}", fails);
}
```

Package versions:
```
lsp-types = "0.56.0"
serde = "1.0.89"
serde_json = "1.0.39"
```

@vnagarnaik what kind of extra field do you have? Is my minimal example any close to the response of your language server in structure?

**Comment by vnagarnaik** [comment]
Sorry it took a while for me to figure out the issue. The parsing does not fail due to extra fields added, but rather due to lack of certain fields. The LSP server seems to be missing these fields:
- `CompletionItem::additionalTextEdits::[range::start::character]`
- `CompletionItem::additionalTextEdits::[range::end::character]`.

After adding the `character` parameter, the parsing works.  Is this an issue with the server missing the field? Or something the client should ignore and succeed in parsing? The canonical VSCode client and other clients seem to be ignoring the lack of that field.

Example failing code:
```
use lsp_types::CompletionResponse;
use serde_json::Result;

fn main() {
    let no_extra = r#"
        {
            "isIncomplete":true,
            "items":[
                {
                    "label":"size_t",
                    "kind":18,
                    "additionalTextEdits":
                    [{
                        "range":
                        {
                            "start":
                            {
                                "line":2
                            },
                            "end":
                            {
                                "line":2
                            }
                        },
                        "newText":"asdf"
                    }]
                }
            ]
        }"#;
    let fine: Result<CompletionResponse> = serde_json::from_str(no_extra);
    println!("Fails: {:?}", fine);
}
```

**Comment by ul** [comment]
The specification defines the `character` field as mandatory in the `Position` interface: https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#position

**Comment by vnagarnaik** [comment]
I agree. We should close this issue. I will file a bug against the server.
